apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: almost-automated-migration-k8s-wait-for
subjects:
  - kind: ServiceAccount
    name: default
    namespace: almost-automated
roleRef:
  kind: Role
  name: almost-automated-migration-k8s-wait-for
  apiGroup: rbac.authorization.k8s.io
