apiVersion: apps/v1
kind: Deployment
metadata:
  name: almost-automated-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: almost-automated-db-deployment
  template:
    metadata:
      labels:
        app: almost-automated-db-deployment
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: DB_HOST
              value: almost-automated-db
            - name: DB_USER
              value: almostapidb
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: almost-automated-db
                  key: password
